### PR TITLE
Issue fix in yml file.

### PR DESCRIPTION
**Pull request by saranya-sajeev**

### CODE REVIEW

**Comment by avaidyam** [comment]
@saranya-sajeev Please revert this change once the CI/CD pipeline finishes building the release. This prevents staging builds from being pushed to the Google Play Console.

**Comment by saranya-sajeev** [comment]
@avaidyam sure Aditya. It is done as a quick fix to  release the build. Will remove after production release and will do the changes in CI/Cd script to work for both push and release events.

**Comment by saranya-sajeev** [comment]
@avaidyam Could you please try to create a new release?

**Comment by avaidyam** [comment]
The [release was already made when I commented earlier](https://github.com/BIDMCDigitalPsychiatry/LAMP-core-android/releases/tag/2022.2.28) and the build failed for the same reason (APK had an APK code already used by a previously uploaded APK).

**Comment by saranya-sajeev** [comment]
@avaidyam we will check.

**Comment by saranya-sajeev** [comment]
@avaidyam CI/CD workflow changes almost completed. Empty commit causes the CI/CD to run again. We are working on it.

**Comment by saranya-sajeev** [comment]
@avaidyam We have fixed the version code issue by adding an empty commit in git for release type. Could you please try to create a new release instead of re-running the existing release.

**Comment by saranya-sajeev** [comment]
@avaidyam We have fixed the issue in work flow for the release. We have tried here with release and it is working fine.

Friday we have checked only in push type and it was working and we thought it will work in release type.


When we are pushing to the master , we are inside a branch and making push from there. But in case of release, we are creating a release out side of a branch and we have to specify the brach to which the commit to be made. After specifying the master branch issue is fixed. Same issue was also there when reading the version code for release. It is also fixed. Everything is working fine and build is uploaded to play store when tried here.

You can try with a tag of 2022.3.8, as we have already tried with 2022.3.7

**Comment by avaidyam** [comment]
Thanks for resolving this issue, @saranya-sajeev!

**Pull request merged**
